{% extends 'layout/base.html.twig' %}

{% block pageTitle %}Error{% endblock %}

{% block content %}
    <div class="container container-page" id="exception_page">
        <div class="page-header pusher">
            <div class="pusher__body">
                <h1>{{ title }}</h1>
            </div>
            <div class="pusher__item__header">
                <a href="javascript:history.back()" class="btn btn-primary">Go Back</a>
            </div>
        </div>
        <div class="row box-sm">
            <div class="col-md-3">
                <label>Message :</label>
            </div>
            <div class="col-md-9">
                <p>{{ message }}</p>
            </div>
        </div>
        <div class="row box-sm">
            <div class="col-md-3">
                <label>Throw in :</label>
            </div>
            <div class="col-md-9">
                <p>{{ throwIn }}</p>
            </div>
        </div>
        <div class="row box-sm">
            <div class="col-md-3">
                <label>Trace :</label>
            </div>
            <div class="col-md-9">
                {% for trace in traces %}
                    <p>{{ trace }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}